import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Montserrat } from 'next/font/google';
import { Ubuntu } from 'next/font/google';
import { Radio_Canada } from 'next/font/google';
import { Quicksand } from 'next/font/google';
import { Roboto_Condensed } from 'next/font/google';
import './globals.css';

const radio_canada = Radio_Canada({
  subsets: ['latin'],
  weight: '400',
});

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: '400',
});

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: '400',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: '400',
});

const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: '400',
});

const inter = Inter({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Here, we define the layout of the website (typically segregate based off user status)
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div>Test</div>
        {children}
      </body>
    </html>
  );
}
